version: '3.8'

services:
  backend1:
    build: backend1/
    container_name: backend1
#    hostname: backend1
    ports:
      - "8081:8080"
      - "2221:22"
    networks:
      - my-network
    privileged: true

  backend2:
    build: backend2/
    container_name: backend2
#    hostname: backend2
    ports:
      - "8082:8080"
      - "2222:22"
    networks:
      - my-network
    privileged: true

  lb1:
    build: lb1/
    container_name: lb1
#    hostname: lb1
    ports:
      - "8085:80"
      - "2223:22"
    networks:
      - my-network
    depends_on:
      - backend1
    privileged: true

  lb2:
    build: lb2/
    container_name: lb2
#   hostname: lb2
    ports:
      - "40000:80"
      - "2224:22"
    networks:
      - my-network
    depends_on:
      - backend2
    privileged: true

  ansible:
    build: ansible/
    ports:
      - "2225:22"
    container_name: ansible
    networks:
      - my-network
    volumes:
      - ./ansible/playbooks:/ansible/playbooks
      - ./ssh:/root/.ssh
      - ./entrypoint.sh:/entrypoint.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#    entrypoint: ["/bin/bash", "service", "ssh", "start", "&&", "/bin/bash", "-c", "sleep infinity"]
    entrypoint: /entrypoint.sh
    depends_on:
      - backend1
      - backend2
      - lb1
      - lb2
    privileged: true

networks:
  my-network:
    driver: bridge

# version: '3.8'

# services:
#   backend1:
#     build: backend1/
#     container_name: backend1
#     ports:
#       - "8081:8080"
#       - "2221:22"
#     networks:
#       - my-network

#   backend2:
#     build: backend2/
#     container_name: backend2
#     ports:
#       - "8082:8080"
#       - "2222:22"
#     networks:
#       - my-network

#   lb1:
#     build: lb1/
#     container_name: lb1
#     ports:
#       - "80:80"
#       - "2223:22"
#     networks:
#       - my-network

#   lb2:
#     build: lb2/
#     container_name: lb2
#     ports:
#       - "81:80"
#       - "2224:22"
#     networks:
#       - my-network

#   ansible:
#     build: ansible/
#     container_name: ansible
#     networks:
#       - my-network
#     volumes:
#       - ./ansible/playbooks:/ansible/playbooks
#       - ./ssh:/root/.ssh
#     entrypoint: ["/bin/sh", "-c", "sleep infinity"]
#     depends_on:
#       - backend1
#       - backend2
#       - lb1
#       - lb2

# networks:
#   my-network:
#     driver: bridge
#     # external: false
