services:
  backend1:
    build: backend1/
    ports:
      - "8080:5001"
  backend2:
    build: backend2/
    ports:
      - "8080:5002"
  lb1:
    build: lb1/
    ports:
      - "80:5003"
  lb2:
    build: lb2/
    ports:
      - "80:5004"
  ansible:
    build: ansible/


networks:
  default:
    internal: true
