    - name: Creating container lb1
      docker_container:
        name: lb1
        volumes:
          - nodes/lb1/nginx.conf:/etc/nginx/nginx.conf

    - name: Creating container lb2
      docker_container:
        name: lb2
        image: debian:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - nodes/lb2/nginx.conf:/etc/nginx/nginx.conf
