- name: Установка и настройка бэкендов
  hosts: backends
  become: yes
  tasks:
    - name: Установить Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Копировать HTML файл
      copy:
        src: /ansible/playbooks/index.html
        dest: /var/www/html/index.html

    - name: Настроить Apache для прослушивания на порту 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        line: "Listen 8080"
        create: yes

    - name: Запустить и включить Apache
      service:
        name: apache2
        state: started
        enabled: yes
  