- name: Установка и настройка балансировщиков
  hosts: loadbalancers
  become: yes
  tasks:
    - name: Установить Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Копировать конфигурацию Nginx
      copy:
        src: /ansible/playbooks/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Запустить и включить Nginx
      service:
        name: nginx
        state: started
        enabled: yes
