  - name: Configure nginx
    hosts: loadbalancers
    tasks:

      - name: Install nginx
        apt:
          name: nginx
          state: present
          update_cache: yes

      - name: Перезапустить Nginx
        service:
          name: nginx
          state: started
          enabled: yes