- name: Creating container lb1
  docker_container:
    name: lb1
    image: debian:latest
    state: started
    ports:
      - "80:5003"
    volumes:
      - /home/igor/Automatrix-Resilient-Cluster/ansible/nodes/lb1/nginx.conf:/etc/nginx/nginx.conf

- name: Creating container lb2
  docker_container:
    name: lb2
    image: debian:latest
    state: started
    ports:
      - "80:5004"
    volumes:
      - /home/igor/Automatrix-Resilient-Cluster/ansible/nodes/lb2/nginx.conf:/etc/nginx/nginx.conf
