
    - name: Install Pacemaker
      pip:
        name:
          - pacemaker
        state: present

    - name: Setup Pacemaker cluster
      command: pcs cluster setup --force --name clustering_lb lb1 lb2
