- name: Copy SSH public key to containers
  hosts: all
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /root/.ssh
        state: directory
        mode: 0700

    - name: Copy SSH public key
      copy:
        src: /root/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        mode: 0600
