  - name: Установить Pacemaker и Corosync
    hosts: loadbalancers
    become: true
    remote_user: root
    tasks:
    
      - name: Установить pacemaker и его зависимости
        apt:
          name: 
            - pacemaker
            - pcs
            - corosync
        notify:
          - restart supervisord

    handlers:
      - import_tasks: handlers/main.yml
