    - name: Установить Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Копировать конфигурацию Nginx
      copy:
        src: /ansible/playbooks/config/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: no

    - name: Перезапустить Nginx
      command: service nginx start


    # - name: Убедиться, что Nginx включен
    #   command: service nginx start