- name: Installation and configuration of balancers
  hosts: lb_hosts
  become: true
  tasks:
    - name: Creating container lb1
      docker_container:
        name: lb1
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - nodes/lb1/nginx.conf:/etc/nginx/nginx.conf

    - name: Creating container lb2
      docker_container:
        name: lb2
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - nodes/lb2/nginx.conf:/etc/nginx/nginx.conf
