- name: Installation and configuration of balancers
  hosts: lb_hosts
  become: true
  tasks:
    - name: Creating container lb1
      docker_container:
        name: lb1
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - ./lb1/nginx.conf:/etc/nginx/nginx.conf
        networks:
          - internal_network

    - name: Creating container lb2
      docker_container:
        name: lb2
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - ./lb2/nginx.conf:/etc/nginx/nginx.conf
        networks:
          - internal_network

networks:
  internal_network:
    driver: bridge

