- name: Main playbook for deploy 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Executing the installation playbook and configuration settings
      include_playbook: playbook_conf-lb.yml

    - name: Executing the installation playbook and configuring balancer clustering
      include_playbook: playbook_conf-cluster-lb.yml

    - name: Executing the installation and configuration playbook backend 
      include_playbook: playbook_conf-backend.yml



