- name: Плейбук установки и настройки балансировщиков
  hosts: lb_nodes
  become: true
  tasks:
    - name: Копирование конфигурационных файлов балансировщика lb1
      copy:
        src: /nodes/lb1/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Копирование конфигурационных файлов балансировщика lb2
      copy:
        src: /nodes/lb2/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Перезапуск сервиса Nginx
      service:
        name: nginx
        state: restarted

