- name: Установка и настройка бэкендов
  hosts: backend_hosts
  become: true
  tasks:
    - name: Создание контейнера backend1
      docker_container:
        name: backend1
        image: debian:latest   # Образ на основе Debian
        state: started
        ports:
          - "8080:80"
        volumes:
          - ./backend1/httpd.conf:/etc/apache2/httpd.conf
          - ./backend1/index.html:/var/www/html/index.html
        networks:
          - internal_network

    - name: Создание контейнера backend2
      docker_container:
        name: backend2
        image: debian:latest   # Образ на основе Debian
        state: started
        ports:
          - "8080:80"
        volumes:
          - ./backend2/httpd.conf:/etc/apache2/httpd.conf
          - ./backend2/index.html:/var/www/html/index.html
        networks:
          - internal_network

networks:
  internal_network:
    driver: bridge


