- name: Главный плейбук для деплоя
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Выполнение плейбука установки и настройки балансировщиков
      include_playbook: playbook_conf-lb.yml

    - name: Выполнение плейбука установки и настройки кластеризации балансировщиков
      include_playbook: playbook_conf-cluster-lb.yml

    - name: Выполнение плейбука установки и настройки бэкенда
      include_playbook: playbook_conf-backend.yml



